# Site settings
title: urbanalytics
email: avc8@uw.edu
url: http://urbanalytics.uw.edu/
meta_author: Avanti Chande
disqus_shortname: Urban

# Build settings
markdown: kramdown
permalink: pretty
port: 4001

# Compression settings
sass:
  sass_dir: ui/_scss
  style: compressed
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false
  startings: [head, body]