# Site settings
title: urbanalytics
email: avc8@uw.edu
url: http://urbanalytics.uw.edu/
meta_author: Avanti Chande
disqus_shortname: Urban

# Build settings
markdown: kramdown
permalink: pretty
port: 4001